# Generated by Django 5.0.2 on 2024-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
                ('genre_description', models.TextField()),
                ('genre_photo', models.ImageField(blank=True, null=True, upload_to='genre_photos/')),
            ],
        ),
    ]
