# Generated by Django 5.0.2 on 2024-06-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_genres', '0003_remove_style_style_genre_style_style_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_genre_name', models.CharField(max_length=100)),
                ('sub_genre_description', models.TextField()),
                ('sub_genre_photo', models.ImageField(blank=True, null=True, upload_to='sub_genre_photos/')),
                ('sub_genre_styles', models.ManyToManyField(related_name='sub_genres', to='dt_genres.style')),
            ],
        ),
    ]
