# Generated by Django 5.0.2 on 2024-05-23 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dt_bands', '0003_instrument_alter_bandmember_band_member_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_date', models.DateTimeField()),
                ('gig_ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gig_link', models.URLField(blank=True, null=True)),
                ('gig_additional_info', models.TextField(blank=True, null=True)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='dt_bands.band')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to='dt_gigs.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_name', models.CharField(max_length=255)),
                ('festival_start_date', models.DateField()),
                ('festival_end_date', models.DateField()),
                ('festival_description', models.TextField(blank=True, null=True)),
                ('festival_link', models.URLField(blank=True, null=True)),
                ('festival_ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bands', models.ManyToManyField(related_name='festivals', to='dt_bands.band')),
                ('venues', models.ManyToManyField(related_name='festivals', to='dt_gigs.venue')),
            ],
        ),
    ]
