# Generated by Django 5.0.2 on 2024-06-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_gigs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='address',
            new_name='venue_address',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='capacity',
            new_name='venue_capacity',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='venue_name',
        ),
        migrations.AddField(
            model_name='festival',
            name='gigs',
            field=models.ManyToManyField(blank=True, related_name='festivals', to='dt_gigs.gig'),
        ),
        migrations.AddField(
            model_name='gig',
            name='gig_setlist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
