# Generated by Django 5.0.2 on 2024-06-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dt_gigs', '0003_setlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='gig_setlist',
        ),
    ]
