# Generated by Django 5.0.2 on 2024-05-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dt_bands', '0003_instrument_alter_bandmember_band_member_instrument'),
        ('dt_genres', '0002_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_address', models.CharField(max_length=255)),
                ('label_country', models.CharField(max_length=100)),
                ('label_description', models.TextField()),
                ('label_founding_date', models.DateField()),
                ('label_name', models.CharField(max_length=100)),
                ('label_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('label_photo', models.ImageField(blank=True, null=True, upload_to='label_photos/')),
                ('label_postal_code', models.CharField(max_length=20)),
                ('label_status', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Temporairement indisponible', 'Temporairement indisponible')], max_length=50)),
                ('label_genres', models.ManyToManyField(related_name='labels', to='dt_genres.genre')),
                ('label_styles', models.ManyToManyField(related_name='labels', to='dt_genres.style')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_condition', models.CharField(choices=[('New', 'Neuf'), ('Used', 'Occasion'), ('Damaged', 'Endommagé'), ('Broken', 'Cassé')], max_length=50)),
                ('record_cover', models.ImageField(blank=True, null=True, upload_to='record_covers/')),
                ('record_format', models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl'), ('Concert Live', 'Concert Live')], max_length=50)),
                ('record_title', models.CharField(max_length=100)),
                ('record_tracklist', models.TextField(blank=True, null=True)),
                ('record_tracklist_side_b', models.TextField(blank=True, null=True)),
                ('record_year', models.IntegerField()),
                ('record_type', models.CharField(choices=[('Official', 'Officiel'), ('Bootleg', 'Bootleg'), ('Burned', 'CD Gravé')], default='Official', max_length=50)),
                ('record_band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dt_bands.band')),
                ('record_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dt_genres.genre')),
                ('record_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dt_records.label')),
                ('record_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dt_genres.style')),
            ],
        ),
    ]
