# Generated by Django 5.0.2 on 2024-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_year',
            field=models.DateField(),
        ),
    ]
