# Generated by Django 5.0.2 on 2024-06-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_records', '0002_alter_record_record_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_founding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_status',
            field=models.CharField(blank=True, choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('Temporairement indisponible', 'Temporairement indisponible')], max_length=50, null=True),
        ),
    ]
