# Generated by Django 5.0.2 on 2024-06-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_bands', '0009_bandmember_band_member_birth_country'),
        ('dt_records', '0003_alter_label_label_address_alter_label_label_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_band_members',
            field=models.ManyToManyField(related_name='records', to='dt_bands.bandmember'),
        ),
    ]
