# Generated by Django 5.0.2 on 2024-06-10 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_genres', '0004_subgenre'),
        ('dt_records', '0004_record_record_band_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_sub_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dt_genres.subgenre'),
        ),
    ]
