# Generated by Django 5.0.2 on 2024-06-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_genres', '0004_subgenre'),
        ('dt_records', '0005_record_record_sub_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_genre',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_style',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_sub_genre',
        ),
        migrations.AddField(
            model_name='record',
            name='record_genres',
            field=models.ManyToManyField(related_name='records', to='dt_genres.genre'),
        ),
        migrations.AddField(
            model_name='record',
            name='record_styles',
            field=models.ManyToManyField(related_name='records', to='dt_genres.style'),
        ),
        migrations.AddField(
            model_name='record',
            name='record_sub_genres',
            field=models.ManyToManyField(blank=True, related_name='records', to='dt_genres.subgenre'),
        ),
    ]
