# Generated by Django 5.0.2 on 2024-06-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_records', '0006_remove_record_record_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_format',
            field=models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl'), ('Audio Live Concert', 'Concert Audio'), ('Video Live Concert', 'Concert Vidéo')], max_length=50),
        ),
    ]
