# Generated by Django 5.0.2 on 2024-06-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_genres', '0004_subgenre'),
        ('dt_records', '0007_alter_record_record_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='label_sub_genres',
            field=models.ManyToManyField(related_name='labels', to='dt_genres.subgenre'),
        ),
    ]
