# Generated by Django 5.0.2 on 2024-06-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_records', '0008_label_label_sub_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_length',
            field=models.CharField(choices=[('Full-length', 'Full-length'), ('EP', 'EP')], default='Full-length', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_format',
            field=models.CharField(choices=[('CD', 'CD'), ('Vinyl 33 RPM', 'Vinyl 33 RPM'), ('Vinyl 45 RPM', 'Vinyl 45 RPM'), ('Audio Live Concert', 'Concert Audio'), ('Video Live Concert', 'Concert Vidéo')], max_length=50),
        ),
    ]
