# Generated by Django 5.0.2 on 2024-06-11 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_records', '0009_record_record_length_alter_record_record_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.IntegerField()),
                ('song_title', models.CharField(max_length=255)),
                ('song_duration', models.DurationField(blank=True, null=True)),
                ('side', models.CharField(choices=[('A', 'Side A'), ('B', 'Side B')], default='A', max_length=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracklist', to='dt_records.record')),
            ],
            options={
                'ordering': ['side', 'song_number'],
                'unique_together': {('record', 'song_number', 'side')},
            },
        ),
    ]
