# Generated by Django 5.0.2 on 2024-05-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_bands', '0002_alter_bandmember_band_member_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(max_length=100, unique=True)),
                ('instrument_description', models.TextField(blank=True, null=True)),
                ('instrument_category', models.CharField(blank=True, choices=[('brass', 'Brass'), ('electronic', 'Electronic'), ('keyboard', 'Keyboard'), ('percussion', 'Percussion'), ('strings', 'Strings'), ('vocal', 'Vocal'), ('wind', 'Wind'), ('woodwind', 'Woodwind')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bandmember',
            name='band_member_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dt_bands.instrument'),
        ),
    ]
