# Generated by Django 5.0.2 on 2024-05-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_bands', '0003_instrument_alter_bandmember_band_member_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandmember',
            old_name='band_member_country',
            new_name='band_member_birth_city',
        ),
        migrations.RenameField(
            model_name='bandmember',
            old_name='band_member_name',
            new_name='band_member_first_name',
        ),
        migrations.AddField(
            model_name='bandmember',
            name='band_member_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bandmember',
            name='band_member_nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
