# Generated by Django 5.0.2 on 2024-05-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_bands', '0004_rename_band_member_country_bandmember_band_member_birth_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandmember',
            name='band_member_instrument',
        ),
        migrations.AddField(
            model_name='bandmember',
            name='band_member_instruments',
            field=models.ManyToManyField(blank=True, to='dt_bands.instrument'),
        ),
    ]
