# Generated by Django 5.0.2 on 2024-06-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_bands', '0005_remove_bandmember_band_member_instrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmember',
            name='band_member_death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
