# Generated by Django 5.0.2 on 2024-06-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_bands', '0006_bandmember_band_member_death_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_photo',
            field=models.ImageField(blank=True, null=True, upload_to='band_photos/'),
        ),
    ]
