# Generated by Django 5.0.2 on 2024-06-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt_bands', '0007_band_band_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='band_separation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='band_status',
            field=models.CharField(choices=[('active', 'Active'), ('hiatus', 'On Hiatus'), ('split_up', 'Split Up')], default='active', max_length=10),
        ),
    ]
